### ISSUE TITLE
Exception: No data stream from device! (CMS50Dplus firmware version 4.6)

### ISSUE THREAD

**Issue by airikka** [atbrask/CMS50Dplus#5]
Hi,
I tried to run this command but got this:

```
$ ./cms50dplus.py -s "2016-07-13 18:13:32" RECORDED /dev/ttyUSB0 /tmp/test
Saving recorded data...
Please wait as the latest session is downloaded...
Traceback (most recent call last):
  File "./cms50dplus.py", line 328, in <module>
    dumpRecordedData(args.starttime, args.serialport, args.output)
  File "./cms50dplus.py", line 303, in dumpRecordedData
    for recordedData in oximeter.getRecordedData(starttime):
  File "./cms50dplus.py", line 228, in getRecordedData
    raise Exception("No data stream from device!")
Exception: No data stream from device!
```

I'm not really sure, but could this be due to a newer firmware version of CMS50D+ (version 4.6)?
Has this python script been tested against 4.6 or only older versions?

Br,
airikka

**Comment by airikka** [comment]
I think I have found the answer to my own question.
I made a script that downloads the data from my CMS50D+ device, and it differs in serial communication.
I have uploaded my script to a new github repository:
https://github.com/airikka/spo2cms50dplus

Br,
airikka
